"""ANCESTRIES - the ancestry-selection data use by character creation (character_creation.py)"""

# Power budget kept roughly proportional across entries - offence-leaning ancestries sacrifice
# armour, defence-leaning ones sacrifice attack, HP-heavy ones sacrifice both. See CLAUDE.md.
ANCESTRIES: dict[str, dict] = {
    "basic":    {"label": "No lineage",                 "attack": 4, "armour": 1, "hp": 20, "intellect": 2, "bonus_skill_point": False,
                 "secondary_effect": None, "secondary_ability_label": "No secondary gift"},
    "ares":     {"label": "Descendant of Ares",         "attack": 5, "armour": 1, "hp": 19, "intellect": 1, "bonus_skill_point": False,
                 "secondary_effect": lambda player: setattr(player, "has_reckless_strength", True),
                 "secondary_ability_label": "Reckless Strength - heavy attack miss chance halves"},
    "athena":   {"label": "Descendant of Athena",       "attack": 3, "armour": 3, "hp": 20, "intellect": 5, "bonus_skill_point": False,
                 "secondary_effect": lambda player: setattr(player, "has_measured_casting", True),
                 "secondary_ability_label": "Measured Casting - spells never go on cooldown"},
    "hermes":   {"label": "Descendant of Hermes",       "attack": 4, "armour": 1, "hp": 20, "intellect": 3, "bonus_skill_point": False,
                 "secondary_effect": lambda player: setattr(player, "has_swift_feet", True),
                 "secondary_ability_label": "Swift Feet - fleeing always succeeds cleanly"},
    "poseidon": {"label": "Descendant of Poseidon",     "attack": 2, "armour": 3, "hp": 23, "intellect": 2, "bonus_skill_point": False,
                 "secondary_effect": lambda player: setattr(player, "has_unyielding_tide", True),
                 "secondary_ability_label": "Unyielding Tide - armour's defence never breaks"},
    "achilles": {"label": "Descendant of Achilles",     "attack": 6, "armour": 1, "hp": 16, "intellect": 1, "bonus_skill_point": False,
                 "secondary_effect": lambda player: setattr(player, "has_berserking", True),
                 "secondary_ability_label": "Berserking - +2 damage at or below half HP"},
    "odysseus": {"label": "Descendant of Odysseus",     "attack": 3, "armour": 1, "hp": 20, "intellect": 4, "bonus_skill_point": True,
                 "secondary_effect": lambda player: setattr(player, "has_silver_tongue", True),
                 "secondary_ability_label": "Silver Tongue - trades never consume your items"},
    "atalanta": {"label": "Descendant of Atalanta",     "attack": 5, "armour": 1, "hp": 18, "intellect": 2, "bonus_skill_point": False,
                 "secondary_effect": lambda player: setattr(player, "can_ranged_without_weapon", True),
                 "secondary_ability_label": "Fleet-Footed - ranged attacks need no weapon"},
    "medusa":   {"label": "Descendant of Medusa",       "attack": 2, "armour": 3, "hp": 21, "intellect": 3, "bonus_skill_point": False,
                 "secondary_effect": lambda player: setattr(player, "has_petrifying_gaze", True),
                 "secondary_ability_label": "Petrifying Gaze - chance to poison on attack"},
    "minotaur": {"label": "Descendant of the Minotaur", "attack": 6, "armour": 0, "hp": 21, "intellect": 0, "bonus_skill_point": False,
                 "secondary_effect": lambda player: setattr(player, "has_bull_rush", True), 
                 "secondary_ability_label": "Bull Rush - bonus damage vs a full-HP target"},
    "cyclops":  {"label": "Descendant of a Cyclops",    "attack": 4, "armour": 1, "hp": 23, "intellect": 0, "bonus_skill_point": False,
                 "secondary_effect": lambda player: setattr(player, "has_iron_hide", True),
                 "secondary_ability_label": "Iron Hide - reduces every hit taken by 1"},
}